[workspace]
authors = ["Bjorge Meulemeester <bjorge.meulemeester@mpinb.mpg.de>"]
channels = ["conda-forge"]
name = "spermull-bonn"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
numpy = ">=2.2.5,<3"
pandas = ">=2.2.3,<3"
jupyter = ">=1.1.1,<2"
osmpythontools = ">=0.3.5,<0.4"
geopy = ">=2.4.1,<3"
tqdm = ">=4.67.1,<5"
selenium = ">=4.31.0,<5"
bs4 = ">=4.13.4,<5"
flask = ">=3.1.0,<4"
werkzeug = ">=3.1.3,<4"
jinja2 = ">=3.1.6,<4"
markupsafe = ">=3.0.2,<4"
click = ">=8.1.8,<9"
itsdangerous = ">=2.2.0,<3"
python-dotenv = ">=1.1.0,<2"
pyproj = ">=3.7.1,<4"
plotly = ">=6.0.1,<7"
geopandas = ">=1.0.1,<2"

[pypi-dependencies]
osmium = ">=4.0.2, <5"
webdriver-manager = ">=4.0.2, <5"
isf-pandas-msgpack = ">=0.2.3, <0.3"
